### ISSUE TITLE
Sign SAML requests

### ISSUE THREAD

**Issue by fenryxo** [CZ-NIC/django-eidas-specific-node#10]
New/changed settings:

* `PROXY_SERVICE_IDENTITY_PROVIDER['KEY_FILE']` renamed to `PROXY_SERVICE_IDENTITY_PROVIDER['ENCRYPTION_KEY_FILE']` (string, optional, default None) - The path of a key to decrypt Identity Provider's authentication response.
* `PROXY_SERVICE_IDENTITY_PROVIDER['SIGNING_KEY_FILE']` (string, optional, default None) - The path to a key to sign authentication requests.

~~Should we reuse `PROXY_SERVICE_IDENTITY_PROVIDER['KEY_FILE']` or add new settings `PROXY_SERVICE_IDENTITY_PROVIDER['SIGNING_KEY_FILE']`?~~

**Comment by tpazderka** [comment]
Can't thinlk about any security considerations against reusing. But I think that it should be optional.

So add new optional setting and if it is missing, reuse the key?

**Comment by fenryxo** [comment]
> So add new optional setting and if it is missing, reuse the key?

That sound ok.

**Comment by jtalir** [comment]
eIDAS actually requires to have different keys for signing and encryption

**Comment by fenryxo** [comment]
Removing label `critical` as CZ NIA doesn't verify request signatures.
