### ISSUE TITLE
CI is stuck

### ISSUE THREAD

**Issue by jiri-janousek** [CZ-NIC/django-eidas-specific-node#105]
https://travis-ci.org/github/CZ-NIC/django-eidas-specific-node/builds/756386448

Also, "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information."

@tpazderka, any ideas?

**Comment by fenryxo** [comment]
It seem to have only long delays before it starts - scheduled  ~10:40, finished ~11:40. Still not ideal.

**Comment by tpazderka** [comment]
Migrated to Github Actions.
