### ISSUE TITLE
Greece can use both country codes GR and EL

### ISSUE THREAD

**Issue by jtalir** [CZ-NIC/django-eidas-specific-node#113]
System for displaying flags expects that Greece is identified by country code GR while Greece may decide to use EL instead. For flexibility, both codes should be supported in Country Selector.

**Comment by fenryxo** [comment]
The [ISO 3166 Alpha-2 code for Greece](https://www.iso.org/obp/ui/#iso:code:3166:GR) is `GR`. Why would they use `EL` for country code??

**Comment by jtalir** [comment]
The use it regularly in EU - https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes

**Comment by fenryxo** [comment]
I need to check which country code standard is used by the eIDAS specification. It seems odd to have two codes for a single country.

**Comment by jtalir** [comment]
As mentioned, they are in process of transition. They started to use GR and now they are after consultation with country representatives changes to EL. The transition may take some time. As with all transitions, to be flexible it's better to expect both codes for some time.

**Comment by fenryxo** [comment]
Ok.
