### ISSUE TITLE
Incomplete copyright/license information

### ISSUE THREAD

**Issue by fenryxo** [CZ-NIC/django-eidas-specific-node#29]
We should specify in README:

* Copyright: `Copyright 2019 CZ.NIC, z. s. p. o.`
* License: `[Licensed under GPL-3+](COPYRIGHT)`
* Flags  `Copyright 2013 Panayiotis Lipiridis`, [MIT license](https://github.com/lipis/flag-icon-css/blob/master/LICENSE)

File `COPYRIGHT`:
```
Copyright (C) 2019 CZ.NIC, z. s. p. o.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

Source files [should contain at least copyright information and a reference to license notice](https://www.gnu.org/licenses/gpl-3.0.en.html#howto):

```py
# Copyright (C) 2019 CZ.NIC, z. s. p. o.
# Licensed under GPL-3+, see file COPYRIGHT.
```

**Comment by fenryxo** [comment]
@jtalir, @tdivis @tpazderka, any thought?

**Comment by tdivis** [comment]
"should" is not "must", IMHO it's awful to add something into each source file, I think it's fine to have licence in the project.

**Comment by tpazderka** [comment]
`COPYRIGHT` file is OK IMHO.

License should also be specified in `setup.py`.

I am against including the information in every file.

**Comment by fenryxo** [comment]
Flags are `Copyright (c) 2013 Panayiotis Lipiridis`, [MIT license](https://github.com/lipis/flag-icon-css/blob/master/LICENSE).
