### ISSUE TITLE
Update SPCountry source in LightRequest for CEF eIDAS Node 2.4

### ISSUE THREAD

**Issue by jtalir** [CZ-NIC/django-eidas-specific-node#82]
Discussion at eIDAS Technical SubGroup about what should be correct place in LightRequest to Specific ProxyService resulted in temporary solution that in version 2.4 it will reuse element CitizenCountryCode. Final solution will be discussed later and one of the option is OriginCountryCode element that is used in current code.
Code should support both OriginCountryCode and CitizenCountryCode as the source for SPCountry in SamlRequest to IdP

**Comment by fenryxo** [comment]
Is there any release date scheduled for eIDAS Node 2.4?

**Comment by jtalir** [comment]
It was released on December 10th - https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eIDAS-Node+version+2.4

**Comment by fenryxo** [comment]
@tpazderka: JTa asks for a release (0.4.1 or 0.5.0) with this feature for admins to deploy it.
