### ISSUE TITLE
Invalid signature while assertions are both signed and encrypted

### ISSUE THREAD

**Issue by samikarvonen** [CZ-NIC/django-eidas-specific-node#89]
This might be related to issue https://github.com/CZ-NIC/django-eidas-specific-node/issues/87.

I updated our specific connector to version 0.6.0 and got it working with assertion encryption disabled. However, when I enable the encryption I get an error from our sp which says the signature of the assertion is not valid. I fixed this issue in our development version by temporarily disabling assertion signing and leaving the encryption on. So I can either have the assertions signed or encrypted but when I enable both the signature of the assertions seems to be invalid.

**Comment by fenryxo** [comment]
We should fix #87 first and then check whether signature verification succeeds. Does the error message of your SP contain any information about why the signature is considered invalid?

**Comment by samikarvonen** [comment]
No I didn't get anything else than "signature is not valid". We could try debugging more if #87 doesn't fix the problem.

**Comment by jtalir** [comment]
Looks like  #87 fixed problem with our SP. But our SP apparently doesn't require signed assertions as well and so there is no guarantee that it validates signatures on assertions if they exists

**Comment by samikarvonen** [comment]
#87 Fixed our problem too.

**Comment by tpazderka** [comment]
Closing as #87 is merged.
